set nobackup
set number
set numberwidth=3
set printoptions=number:y
set hlsearch
set ruler
"set encoding=utf8
"set fileencoding=utf8

" Indent settings. Detect filetype, or use auto & smart indent together.
filetype plugin indent on
"set autoindent
"set smartindent
""set cindent

" 256 color mode
" Don't need this. Vim reads number of colors from $TERM.
"if $COLORTERM == 'gnome-terminal'
"set t_Co=256
"endif

syntax on

" Tab settings.
set tabstop=4
set shiftwidth=4
set expandtab

" Text width, auto word wrap. 0 off.
set tw=0
"set tw=100
" Default textwidth for markdown and text files.
au BufRead,BufNewFile *.md setlocal textwidth=100
au BufRead,BufNewFile *.txt setlocal textwidth=100

" Disable all blinking:
set guicursor+=a:blinkon0
" Remove previous setting:
":set guicursor-=a:blinkon0
" Restore default setting:
":set guicursor&

" Disable highlighting until a search. Toggle with ??.
let hlstate=0
nnoremap ?? :if (hlstate == 0) \| nohlsearch \| else \| set hlsearch \| endif \| let hlstate=1-hlstate <CR><CR>

"color darkblue
color elflord
"color twilight256
"color default
"colors zellner
"color desert
"color evening
"color murphy
"color torte
"color slate
"color zenburn
set background=dark

" Mappings

" Disable middle mouse
map <MiddleMouse> <Nop>
imap <MiddleMouse> <Nop>
map <2-MiddleMouse> <Nop>
imap <2-MiddleMouse> <Nop>
map <3-MiddleMouse> <Nop>
imap <3-MiddleMouse> <Nop>
map <4-MiddleMouse> <Nop>
imap <4-MiddleMouse> <Nop>

" Scrolling
nmap <Up> 
nmap <Down> 
nmap <Left> 5
nmap <Right> 5

nmap <Space> <Nop>
let mapleader=" "
map <Leader>y "+y
map <Leader>Y "+y$
"map <Leader>d "+d
"map <Leader>D "+D
"map <Leader>x "+x
"map <Leader>X "+X
"map <Leader>c "+c
"map <Leader>C "+C
"map <Leader>s "+s
"map <Leader>S "+S
map <Leader>p "+p
map <Leader>P "+P

nmap <C-Enter> "+p
imap <C-Enter> <C-R>+

nmap <Leader>w :w<CR>
nmap <Leader>q :q<CR>
nmap <Leader>x :wq<CR>

nmap <Leader>s :Vex<CR>
nmap <Leader>v :vnew<CR>
nmap <Leader>d :diffthis<CR><C-w>w:diffthis<CR><C-w>w
nmap <Leader>e :Ex<CR>

nmap <Leader>o o<ESC>o
nmap <Leader>O O<ESC>O
nmap <Leader><CR> o<ESC>o<ESC>O

nmap <Leader>h 5h
nmap <Leader>j 5j
nmap <Leader>k 5k
nmap <Leader>l 5l

nmap <Leader>c o// 
nmap <Leader>C O// 
nmap <Leader>t o// TODO: 
nmap <Leader>T O// TODO: 

"nmap <Leader>s i r
"nmap <Leader>S a r
nmap <Leader>i i r
nmap <Leader>a a r

" Convert property into assignment.
nmap <Leader>n ^WWElD^dwdWA = , // p==

nnoremap Y y$
nnoremap S ^C

nmap <Leader>/ I// <Esc>$
nmap // I// <Esc>$
nmap ?? ^dw

vmap y ygv<Esc>
vmap <CR> "+y
vmap <Leader>y "+y

nmap <CR> o<Esc>
nmap <S-Enter> O<Esc>
imap <S-Enter> O

" Mash jk to return to normal mode. kk to enter single command.
imap jj <Esc>
imap jk <Esc>
imap kj <Esc>
imap kk 

nmap n nzz
nmap N Nzz

" Enter to return to normal mode. Shift-Enter or Enter to return to insert with newline.
"nmap <S-Enter> o<Esc>
"imap <CR> <Esc>
"inoremap <S-Enter> <CR>

nmap <F4> "=strftime("%Y-%m-%dT%H:%M:%S.0000000Z")<CR>p
imap <F4> =strftime("%Y-%m-%dT%H:%M:%S.0000000Z")<CR>
nmap <F3> "=strftime("%d/%m/%Y %H:%M:%S")<CR>p
imap <F3> =strftime("%d/%m/%Y %H:%M:%S")<CR>
