" Disable mouse
set mouse=c

syntax on

" Set font for MS Windows
"set guifont=Consolas:h11
" Or for Linux
set guifont=Monospace\ 11

" Window size
"set lines=40 columns=100
set lines=45 columns=130
"set lines=48 columns=150

" Maximise window for MS Windows
"au GUIEnter * simalt ~x

"set guioptions-=m  "remove menu bar
"set guioptions-=T  "remove toolbar
"set guioptions-=r  "remove right-hand scroll bar
"set guioptions-=L  "remove left-hand scroll bar

