" Disable mouse
set mouse=c

if has("win32")
    " Set font for MS Windows
    set guifont=Consolas:h11
    "set guifont=Courier:h12
    "set guifont=Courier10\ BT:h11
    "set guifont=Terminus:h12
elseif has("unix")
    " Or for Linux
    set guifont=Monospace\ 11
    "set guifont=Liberation\ Mono\ 10
    "set guifont=Terminus\ 12
endif

" Window size
"set lines=40 columns=100
set lines=45 columns=130
"set lines=48 columns=150

" Maximise window for MS Windows
"au GUIEnter * simalt ~x

"set guioptions-=m  "remove menu bar
"set guioptions-=T  "remove toolbar
"set guioptions-=r  "remove right-hand scroll bar
"set guioptions-=L  "remove left-hand scroll bar

